dekick:
  boilerplate: express/default
  flavour: next
  ports:
    - port: 3000
      service: web
gitlab:
  getenv: true
  url: https://git.desmart.com/
project:
  artifacts:
    - path: .yarn/cache/
    - path: .yarn/install-state.gz
    - path: node_modules/
  environments:
    - name: test
    - name: production
  group: quantumadr
  name: front
  providers:
    credentials:
      driver: gitlab
